import type { Config } from "tailwindcss";

// MNEMOS Mission Control design system.
// Extracted verbatim from the Stitch page exports so every route reads as one system.
const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        error: "#ffb4ab",
        "secondary-fixed": "#ffddb5",
        "outline-variant": "#3c494c",
        "on-error": "#690005",
        "on-secondary-fixed": "#2a1800",
        "on-background": "#dde4e5",
        "tertiary-container": "#ffaba0",
        outline: "#859397",
        "tertiary-fixed-dim": "#ffb4aa",
        "surface-container-highest": "#2f3638",
        "surface-container-high": "#242b2d",
        "surface-variant": "#2f3638",
        "surface-container-low": "#161d1e",
        "on-primary-fixed": "#001f25",
        "primary-fixed-dim": "#2fd9f4",
        tertiary: "#ffd2cc",
        "surface-container": "#1a2122",
        "on-secondary-container": "#4c2f00",
        "surface-tint": "#2fd9f4",
        "on-tertiary-container": "#a20008",
        "on-secondary-fixed-variant": "#643f00",
        "on-surface": "#dde4e5",
        "secondary-container": "#d98e00",
        secondary: "#ffb957",
        "surface-container-lowest": "#090f11",
        "secondary-fixed-dim": "#ffb957",
        "surface-dim": "#0e1416",
        "on-error-container": "#ffdad6",
        "primary-container": "#22d3ee",
        "inverse-primary": "#006877",
        "on-primary-fixed-variant": "#004e5a",
        surface: "#0e1416",
        "on-tertiary-fixed": "#410001",
        "on-primary-container": "#005763",
        "inverse-on-surface": "#2b3233",
        "inverse-surface": "#dde4e5",
        "on-secondary": "#462b00",
        "on-surface-variant": "#bbc9cd",
        "on-tertiary": "#690003",
        "on-tertiary-fixed-variant": "#930006",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffdad5",
        background: "#0e1416",
        "surface-bright": "#343a3c",
        "primary-fixed": "#a2eeff",
        "on-primary": "#00363e",
        primary: "#8aebff",
        // Darker terminal levels a few pages reference directly.
        "level-0": "#0A0E14",
        "level-1": "#111721",
        "level-2": "#1E2A38",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        top_bar_height: "56px",
        tight_stack: "4px",
        gutter: "12px",
        panel_padding: "16px",
        nav_rail_width: "64px",
      },
      fontFamily: {
        "display-id": ["var(--font-jetbrains)", "monospace"],
        "label-caps": ["var(--font-jetbrains)", "monospace"],
        "data-mono-bold": ["var(--font-jetbrains)", "monospace"],
        "data-mono": ["var(--font-jetbrains)", "monospace"],
        "headline-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
      },
      fontSize: {
        "display-id": ["24px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "data-mono-bold": ["13px", { lineHeight: "18px", fontWeight: "600" }],
        "headline-md": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};

export default config;
